-- Stock Manager: Initial schema for Supabase PostgreSQL

CREATE TABLE portfolios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(200) DEFAULT '',
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE stocks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id      BIGINT NOT NULL REFERENCES portfolios(id) ON DELETE CASCADE,
    code              VARCHAR(10) NOT NULL,
    name              VARCHAR(50) NOT NULL,
    market            VARCHAR(5) NOT NULL,
    cost_price        NUMERIC(15,4) NOT NULL DEFAULT 0,
    current_price     NUMERIC(15,4) NOT NULL DEFAULT 0,
    prev_close_price  NUMERIC(15,4) NOT NULL DEFAULT 0,
    quantity          INTEGER NOT NULL DEFAULT 0,
    status            VARCHAR(10) NOT NULL DEFAULT 'holding',
    stop_loss_price   NUMERIC(15,4),
    take_profit_price NUMERIC(15,4),
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    updated_at        TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_portfolio_code UNIQUE (portfolio_id, code)
);
CREATE INDEX idx_stocks_code ON stocks(code);
CREATE INDEX idx_stocks_portfolio ON stocks(portfolio_id);

CREATE TABLE trade_logs (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id   BIGINT NOT NULL REFERENCES stocks(id) ON DELETE CASCADE,
    action     VARCHAR(20) NOT NULL,
    price      NUMERIC(15,4) NOT NULL DEFAULT 0,
    quantity   INTEGER NOT NULL DEFAULT 0,
    note       TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_trade_logs_stock ON trade_logs(stock_id);
CREATE INDEX idx_trade_logs_created ON trade_logs(created_at DESC);

CREATE TABLE daily_snapshots (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id                 BIGINT NOT NULL REFERENCES stocks(id) ON DELETE CASCADE,
    date                     DATE NOT NULL,
    close_price              NUMERIC(15,4) NOT NULL DEFAULT 0,
    cost_price_snapshot      NUMERIC(15,4) NOT NULL DEFAULT 0,
    quantity_snapshot        INTEGER NOT NULL DEFAULT 0,
    market_value_snapshot    NUMERIC(15,4) NOT NULL DEFAULT 0,
    profit_loss_pct_snapshot NUMERIC(15,4) NOT NULL DEFAULT 0,
    CONSTRAINT uq_stock_date UNIQUE (stock_id, date)
);
CREATE INDEX idx_snapshots_stock ON daily_snapshots(stock_id);

-- RLS policies (single user, no auth initially)
ALTER TABLE portfolios ENABLE ROW LEVEL SECURITY;
ALTER TABLE stocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE trade_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_snapshots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all on portfolios" ON portfolios FOR ALL USING (true);
CREATE POLICY "Allow all on stocks" ON stocks FOR ALL USING (true);
CREATE POLICY "Allow all on trade_logs" ON trade_logs FOR ALL USING (true);
CREATE POLICY "Allow all on daily_snapshots" ON daily_snapshots FOR ALL USING (true);
