-- Daily Notes: User's daily journal/summary

CREATE TABLE daily_notes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date       DATE NOT NULL UNIQUE,
    content    TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE daily_notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all on daily_notes" ON daily_notes FOR ALL USING (true);
